// Code generated by protoc-gen-go.
// source: tensorflow/core/protobuf/config.proto
// DO NOT EDIT!

package tensorflow

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import tensorflow1 "tensorflow/core/framework"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Optimization level
type OptimizerOptions_Level int32

const (
	// L1 is the default level.
	// Optimization performed at L1 :
	// 1. Common subexpression elimination
	// 2. Constant folding
	OptimizerOptions_L1 OptimizerOptions_Level = 0
	// No optimizations
	OptimizerOptions_L0 OptimizerOptions_Level = -1
)

var OptimizerOptions_Level_name = map[int32]string{
	0:  "L1",
	-1: "L0",
}
var OptimizerOptions_Level_value = map[string]int32{
	"L1": 0,
	"L0": -1,
}

func (x OptimizerOptions_Level) String() string {
	return proto.EnumName(OptimizerOptions_Level_name, int32(x))
}
func (OptimizerOptions_Level) EnumDescriptor() ([]byte, []int) { return fileDescriptor16, []int{1, 0} }

type RunOptions_TraceLevel int32

const (
	RunOptions_NO_TRACE   RunOptions_TraceLevel = 0
	RunOptions_FULL_TRACE RunOptions_TraceLevel = 1
)

var RunOptions_TraceLevel_name = map[int32]string{
	0: "NO_TRACE",
	1: "FULL_TRACE",
}
var RunOptions_TraceLevel_value = map[string]int32{
	"NO_TRACE":   0,
	"FULL_TRACE": 1,
}

func (x RunOptions_TraceLevel) String() string {
	return proto.EnumName(RunOptions_TraceLevel_name, int32(x))
}
func (RunOptions_TraceLevel) EnumDescriptor() ([]byte, []int) { return fileDescriptor16, []int{5, 0} }

type GPUOptions struct {
	// A value between 0 and 1 that indicates what fraction of the
	// available GPU memory to pre-allocate for each process.  1 means
	// to pre-allocate all of the GPU memory, 0.5 means the process
	// allocates ~50% of the available GPU memory.
	PerProcessGpuMemoryFraction float64 `protobuf:"fixed64,1,opt,name=per_process_gpu_memory_fraction,json=perProcessGpuMemoryFraction" json:"per_process_gpu_memory_fraction,omitempty"`
	// The type of GPU allocation strategy to use.
	//
	// Allowed values:
	// "": The empty string (default) uses a system-chosen default
	//     which may change over time.
	//
	// "BFC": A "Best-fit with coalescing" algorithm, simplified from a
	//        version of dlmalloc.
	AllocatorType string `protobuf:"bytes,2,opt,name=allocator_type,json=allocatorType" json:"allocator_type,omitempty"`
	// Delay deletion of up to this many bytes to reduce the number of
	// interactions with gpu driver code.  If 0, the system chooses
	// a reasonable default (several MBs).
	DeferredDeletionBytes int64 `protobuf:"varint,3,opt,name=deferred_deletion_bytes,json=deferredDeletionBytes" json:"deferred_deletion_bytes,omitempty"`
	// If true, the allocator does not pre-allocate the entire specified
	// GPU memory region, instead starting small and growing as needed.
	AllowGrowth bool `protobuf:"varint,4,opt,name=allow_growth,json=allowGrowth" json:"allow_growth,omitempty"`
}

func (m *GPUOptions) Reset()                    { *m = GPUOptions{} }
func (m *GPUOptions) String() string            { return proto.CompactTextString(m) }
func (*GPUOptions) ProtoMessage()               {}
func (*GPUOptions) Descriptor() ([]byte, []int) { return fileDescriptor16, []int{0} }

// Options passed to the graph optimizer
type OptimizerOptions struct {
	// If true, optimize the graph using common subexpression elimination.
	DoCommonSubexpressionElimination bool `protobuf:"varint,1,opt,name=do_common_subexpression_elimination,json=doCommonSubexpressionElimination" json:"do_common_subexpression_elimination,omitempty"`
	// If true, perform constant folding optimization on the graph.
	DoConstantFolding bool `protobuf:"varint,2,opt,name=do_constant_folding,json=doConstantFolding" json:"do_constant_folding,omitempty"`
	// If true, perform function inlining on the graph.
	DoFunctionInlining bool                   `protobuf:"varint,4,opt,name=do_function_inlining,json=doFunctionInlining" json:"do_function_inlining,omitempty"`
	OptLevel           OptimizerOptions_Level `protobuf:"varint,3,opt,name=opt_level,json=optLevel,enum=tensorflow.OptimizerOptions_Level" json:"opt_level,omitempty"`
}

func (m *OptimizerOptions) Reset()                    { *m = OptimizerOptions{} }
func (m *OptimizerOptions) String() string            { return proto.CompactTextString(m) }
func (*OptimizerOptions) ProtoMessage()               {}
func (*OptimizerOptions) Descriptor() ([]byte, []int) { return fileDescriptor16, []int{1} }

type GraphOptions struct {
	// If true, use control flow to schedule the activation of Recv nodes.
	// (Currently ignored.)
	EnableRecvScheduling bool `protobuf:"varint,2,opt,name=enable_recv_scheduling,json=enableRecvScheduling" json:"enable_recv_scheduling,omitempty"`
	// Options controlling how graph is optimized.
	OptimizerOptions *OptimizerOptions `protobuf:"bytes,3,opt,name=optimizer_options,json=optimizerOptions" json:"optimizer_options,omitempty"`
	// The number of steps to run before returning a cost model detailing
	// the memory usage and performance of each node of the graph. 0 means
	// no cost model.
	BuildCostModel int64 `protobuf:"varint,4,opt,name=build_cost_model,json=buildCostModel" json:"build_cost_model,omitempty"`
	// Annotate each Node with Op output shape data, to the extent it can
	// be statically inferred.
	InferShapes bool `protobuf:"varint,5,opt,name=infer_shapes,json=inferShapes" json:"infer_shapes,omitempty"`
	// Only place the subgraphs that are run, rather than the entire graph.
	//
	// This is useful for interactive graph building, where one might
	// produce graphs that cannot be placed during the debugging
	// process.  In particular, it allows the client to continue work in
	// a session after adding a node to a graph whose placement
	// constraints are unsatisfiable.
	PlacePrunedGraph bool `protobuf:"varint,6,opt,name=place_pruned_graph,json=placePrunedGraph" json:"place_pruned_graph,omitempty"`
}

func (m *GraphOptions) Reset()                    { *m = GraphOptions{} }
func (m *GraphOptions) String() string            { return proto.CompactTextString(m) }
func (*GraphOptions) ProtoMessage()               {}
func (*GraphOptions) Descriptor() ([]byte, []int) { return fileDescriptor16, []int{2} }

func (m *GraphOptions) GetOptimizerOptions() *OptimizerOptions {
	if m != nil {
		return m.OptimizerOptions
	}
	return nil
}

type ThreadPoolOptionProto struct {
	// The number of threads in the pool.
	//
	// 0 means the system picks a value based on where this option proto is used
	// (see the declaration of the specific field for more info).
	NumThreads int32 `protobuf:"varint,1,opt,name=num_threads,json=numThreads" json:"num_threads,omitempty"`
}

func (m *ThreadPoolOptionProto) Reset()                    { *m = ThreadPoolOptionProto{} }
func (m *ThreadPoolOptionProto) String() string            { return proto.CompactTextString(m) }
func (*ThreadPoolOptionProto) ProtoMessage()               {}
func (*ThreadPoolOptionProto) Descriptor() ([]byte, []int) { return fileDescriptor16, []int{3} }

// Session configuration parameters.
// The system picks an appropriate values for fields that are not set.
type ConfigProto struct {
	// Map from device type name (e.g., "CPU" or "GPU" ) to maximum
	// number of devices of that type to use.  If a particular device
	// type is not found in the map, the system picks an appropriate
	// number.
	DeviceCount map[string]int32 `protobuf:"bytes,1,rep,name=device_count,json=deviceCount" json:"device_count,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// The execution of an individual op (for some op types) can be
	// parallelized on a pool of intra_op_parallelism_threads.
	// 0 means the system picks an appropriate number.
	IntraOpParallelismThreads int32 `protobuf:"varint,2,opt,name=intra_op_parallelism_threads,json=intraOpParallelismThreads" json:"intra_op_parallelism_threads,omitempty"`
	// Nodes that perform blocking operations are enqueued on a pool of
	// inter_op_parallelism_threads available in each process.
	//
	// 0 means the system picks an appropriate number.
	//
	// Note that the first Session created in the process sets the
	// number of threads for all future sessions unless use_per_session_threads is
	// true or session_inter_op_thread_pool is configured.
	InterOpParallelismThreads int32 `protobuf:"varint,5,opt,name=inter_op_parallelism_threads,json=interOpParallelismThreads" json:"inter_op_parallelism_threads,omitempty"`
	// If true, use a new set of threads for this session rather than the global
	// pool of threads. Only supported by direct sessions.
	//
	// If false, use the global threads created by the first session, or the
	// per-session thread pools configured by session_inter_op_thread_pool.
	//
	// This option is deprecated. The same effect can be achieved by setting
	// session_inter_op_thread_pool to have one element, whose num_threads equals
	// inter_op_parallelism_threads.
	UsePerSessionThreads bool `protobuf:"varint,9,opt,name=use_per_session_threads,json=usePerSessionThreads" json:"use_per_session_threads,omitempty"`
	// Configures session thread pools. If this is configured, then RunOptions for
	// a Run call can select the thread pool to use.
	//
	// If a pool's num_threads is 0, then inter_op_parallelism_threads is used.
	SessionInterOpThreadPool []*ThreadPoolOptionProto `protobuf:"bytes,12,rep,name=session_inter_op_thread_pool,json=sessionInterOpThreadPool" json:"session_inter_op_thread_pool,omitempty"`
	// Assignment of Nodes to Devices is recomputed every placement_period
	// steps until the system warms up (at which point the recomputation
	// typically slows down automatically).
	PlacementPeriod int32 `protobuf:"varint,3,opt,name=placement_period,json=placementPeriod" json:"placement_period,omitempty"`
	// When any filters are present sessions will ignore all devices which do not
	// match the filters. Each filter can be partially specified, e.g. "/job:ps"
	// "/job:worker/replica:3", etc.
	DeviceFilters []string `protobuf:"bytes,4,rep,name=device_filters,json=deviceFilters" json:"device_filters,omitempty"`
	// Options that apply to all GPUs.
	GpuOptions *GPUOptions `protobuf:"bytes,6,opt,name=gpu_options,json=gpuOptions" json:"gpu_options,omitempty"`
	// Whether soft placement is allowed. If allow_soft_placement is true,
	// an op will be placed on CPU if
	//   1. there's no GPU implementation for the OP
	// or
	//   2. no GPU devices are known or registered
	// or
	//   3. need to co-locate with reftype input(s) which are from CPU.
	AllowSoftPlacement bool `protobuf:"varint,7,opt,name=allow_soft_placement,json=allowSoftPlacement" json:"allow_soft_placement,omitempty"`
	// Whether device placements should be logged.
	LogDevicePlacement bool `protobuf:"varint,8,opt,name=log_device_placement,json=logDevicePlacement" json:"log_device_placement,omitempty"`
	// Options that apply to all graphs.
	GraphOptions *GraphOptions `protobuf:"bytes,10,opt,name=graph_options,json=graphOptions" json:"graph_options,omitempty"`
	// Global timeout for all blocking operations in this session.  If non-zero,
	// and not overridden on a per-operation basis, this value will be used as the
	// deadline for all blocking operations.
	OperationTimeoutInMs int64 `protobuf:"varint,11,opt,name=operation_timeout_in_ms,json=operationTimeoutInMs" json:"operation_timeout_in_ms,omitempty"`
}

func (m *ConfigProto) Reset()                    { *m = ConfigProto{} }
func (m *ConfigProto) String() string            { return proto.CompactTextString(m) }
func (*ConfigProto) ProtoMessage()               {}
func (*ConfigProto) Descriptor() ([]byte, []int) { return fileDescriptor16, []int{4} }

func (m *ConfigProto) GetDeviceCount() map[string]int32 {
	if m != nil {
		return m.DeviceCount
	}
	return nil
}

func (m *ConfigProto) GetSessionInterOpThreadPool() []*ThreadPoolOptionProto {
	if m != nil {
		return m.SessionInterOpThreadPool
	}
	return nil
}

func (m *ConfigProto) GetGpuOptions() *GPUOptions {
	if m != nil {
		return m.GpuOptions
	}
	return nil
}

func (m *ConfigProto) GetGraphOptions() *GraphOptions {
	if m != nil {
		return m.GraphOptions
	}
	return nil
}

// EXPERIMENTAL. Options for a single Run() call.
type RunOptions struct {
	TraceLevel RunOptions_TraceLevel `protobuf:"varint,1,opt,name=trace_level,json=traceLevel,enum=tensorflow.RunOptions_TraceLevel" json:"trace_level,omitempty"`
	// Time to wait for operation to complete in milliseconds.
	TimeoutInMs int64 `protobuf:"varint,2,opt,name=timeout_in_ms,json=timeoutInMs" json:"timeout_in_ms,omitempty"`
	// The thread pool to use, if session_inter_op_thread_pool is configured.
	InterOpThreadPool int32 `protobuf:"varint,3,opt,name=inter_op_thread_pool,json=interOpThreadPool" json:"inter_op_thread_pool,omitempty"`
}

func (m *RunOptions) Reset()                    { *m = RunOptions{} }
func (m *RunOptions) String() string            { return proto.CompactTextString(m) }
func (*RunOptions) ProtoMessage()               {}
func (*RunOptions) Descriptor() ([]byte, []int) { return fileDescriptor16, []int{5} }

// EXPERIMENTAL. Metadata output (i.e., non-Tensor) for a single Run() call.
type RunMetadata struct {
	// Statistics traced for this step. Populated if tracing is turned on via the
	// "RunOptions" proto.
	// EXPERIMENTAL: The format and set of events may change in future versions.
	StepStats *StepStats `protobuf:"bytes,1,opt,name=step_stats,json=stepStats" json:"step_stats,omitempty"`
	// The cost graph for the computation defined by the run call.
	CostGraph *tensorflow1.CostGraphDef `protobuf:"bytes,2,opt,name=cost_graph,json=costGraph" json:"cost_graph,omitempty"`
}

func (m *RunMetadata) Reset()                    { *m = RunMetadata{} }
func (m *RunMetadata) String() string            { return proto.CompactTextString(m) }
func (*RunMetadata) ProtoMessage()               {}
func (*RunMetadata) Descriptor() ([]byte, []int) { return fileDescriptor16, []int{6} }

func (m *RunMetadata) GetStepStats() *StepStats {
	if m != nil {
		return m.StepStats
	}
	return nil
}

func (m *RunMetadata) GetCostGraph() *tensorflow1.CostGraphDef {
	if m != nil {
		return m.CostGraph
	}
	return nil
}

func init() {
	proto.RegisterType((*GPUOptions)(nil), "tensorflow.GPUOptions")
	proto.RegisterType((*OptimizerOptions)(nil), "tensorflow.OptimizerOptions")
	proto.RegisterType((*GraphOptions)(nil), "tensorflow.GraphOptions")
	proto.RegisterType((*ThreadPoolOptionProto)(nil), "tensorflow.ThreadPoolOptionProto")
	proto.RegisterType((*ConfigProto)(nil), "tensorflow.ConfigProto")
	proto.RegisterType((*RunOptions)(nil), "tensorflow.RunOptions")
	proto.RegisterType((*RunMetadata)(nil), "tensorflow.RunMetadata")
	proto.RegisterEnum("tensorflow.OptimizerOptions_Level", OptimizerOptions_Level_name, OptimizerOptions_Level_value)
	proto.RegisterEnum("tensorflow.RunOptions_TraceLevel", RunOptions_TraceLevel_name, RunOptions_TraceLevel_value)
}

func init() { proto.RegisterFile("tensorflow/core/protobuf/config.proto", fileDescriptor16) }

var fileDescriptor16 = []byte{
	// 1067 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x56, 0x6d, 0x6f, 0xe3, 0x44,
	0x10, 0x26, 0xc9, 0xa5, 0x24, 0xe3, 0xb4, 0x97, 0x9a, 0xf6, 0xce, 0x1c, 0x95, 0xae, 0x67, 0x54,
	0xa9, 0x54, 0x28, 0x3d, 0xca, 0xdb, 0x09, 0x09, 0x10, 0x7d, 0x55, 0xa1, 0xa5, 0xd1, 0xa6, 0xf7,
	0x79, 0xe5, 0xc4, 0x9b, 0xd4, 0xaa, 0xe3, 0xb5, 0xbc, 0xeb, 0x96, 0x20, 0xfe, 0x09, 0xdf, 0xf9,
	0x0b, 0xfc, 0x0e, 0x24, 0xfe, 0x0f, 0xcc, 0xce, 0xda, 0x71, 0x1a, 0x55, 0x77, 0xfd, 0x52, 0xef,
	0x3c, 0xcf, 0xac, 0x9f, 0x9d, 0x79, 0x76, 0x1c, 0xd8, 0xd1, 0x22, 0x51, 0x32, 0x1b, 0xc7, 0xf2,
	0x7e, 0x7f, 0x24, 0x33, 0xb1, 0x9f, 0x66, 0x52, 0xcb, 0x61, 0x3e, 0xc6, 0x55, 0x32, 0x8e, 0x26,
	0x3d, 0x5a, 0xbb, 0x50, 0xd1, 0x5e, 0xec, 0x2d, 0xa7, 0x8c, 0xb3, 0x60, 0x2a, 0xee, 0x65, 0x76,
	0x8b, 0x4b, 0xa5, 0xf9, 0x24, 0x0b, 0xd2, 0x1b, 0x9b, 0xf7, 0x2e, 0xae, 0xd2, 0x22, 0xe5, 0x4a,
	0x07, 0x5a, 0x59, 0xae, 0xff, 0x6f, 0x0d, 0xe0, 0xac, 0xff, 0xf6, 0x2a, 0xd5, 0x91, 0x4c, 0x94,
	0x7b, 0x0c, 0x2f, 0x53, 0x91, 0x71, 0xc4, 0x46, 0x42, 0x29, 0x3e, 0x49, 0x73, 0x3e, 0x15, 0x53,
	0x99, 0xcd, 0x38, 0xee, 0x31, 0x32, 0x1c, 0xaf, 0xb6, 0x5d, 0xdb, 0xad, 0xb1, 0x4f, 0x90, 0xd6,
	0xb7, 0xac, 0xb3, 0x34, 0xbf, 0x24, 0xce, 0x69, 0x41, 0x71, 0x77, 0x60, 0x2d, 0x88, 0x63, 0x39,
	0x0a, 0xb4, 0xcc, 0xb8, 0x9e, 0xa5, 0xc2, 0xab, 0x63, 0x52, 0x9b, 0xad, 0xce, 0xa3, 0xd7, 0x18,
	0x74, 0xbf, 0x81, 0xe7, 0xa1, 0x18, 0x8b, 0x2c, 0x13, 0x21, 0x0f, 0x45, 0x2c, 0x4c, 0x2e, 0x1f,
	0xce, 0xb4, 0x50, 0x5e, 0x03, 0xf9, 0x0d, 0xb6, 0x59, 0xc2, 0xc7, 0x05, 0x7a, 0x68, 0x40, 0xf7,
	0x15, 0x74, 0xcc, 0x46, 0xf7, 0x78, 0x68, 0x79, 0xaf, 0x6f, 0xbc, 0x27, 0x48, 0x6e, 0x31, 0x87,
	0x62, 0x67, 0x14, 0xf2, 0xff, 0xaa, 0x43, 0xd7, 0x9c, 0x69, 0x1a, 0xfd, 0x2e, 0xb2, 0xf2, 0x70,
	0x97, 0xf0, 0x69, 0x28, 0xf9, 0x48, 0x4e, 0xa7, 0xf8, 0x1e, 0x95, 0x0f, 0xc5, 0x6f, 0x69, 0x86,
	0xfa, 0xcd, 0x5b, 0x45, 0x8c, 0xd4, 0x24, 0x98, 0x1f, 0xb0, 0xc5, 0xb6, 0x43, 0x79, 0x44, 0xcc,
	0xc1, 0x22, 0xf1, 0xa4, 0xe2, 0xb9, 0x3d, 0xf8, 0x88, 0xb6, 0x4b, 0xb0, 0x9e, 0x89, 0xe6, 0x63,
	0x19, 0x87, 0x51, 0x32, 0xa1, 0xa3, 0xb6, 0xd8, 0xba, 0x49, 0xb7, 0xc8, 0xa9, 0x05, 0xdc, 0xd7,
	0xb0, 0x81, 0xfc, 0x71, 0x9e, 0x50, 0x91, 0x78, 0x94, 0xc4, 0x51, 0x62, 0x12, 0xac, 0x7c, 0x37,
	0x94, 0xa7, 0x05, 0x74, 0x5e, 0x20, 0xee, 0x8f, 0xd0, 0x96, 0xa9, 0xe6, 0xb1, 0xb8, 0x13, 0x31,
	0x95, 0x64, 0xed, 0xc0, 0xef, 0x55, 0xcd, 0xed, 0x2d, 0x9f, 0xb0, 0x77, 0x61, 0x98, 0xac, 0x85,
	0x49, 0xf4, 0xe4, 0x6f, 0x43, 0x93, 0x1e, 0xdc, 0x15, 0xa8, 0x5f, 0x7c, 0xd1, 0xfd, 0xc0, 0x7d,
	0x8a, 0xff, 0x5f, 0x77, 0xff, 0x2b, 0xff, 0x6a, 0xfe, 0xdf, 0x75, 0xe8, 0x9c, 0x19, 0xef, 0x94,
	0x45, 0xfa, 0x0a, 0x9e, 0x89, 0x24, 0x18, 0xc6, 0x82, 0x67, 0x62, 0x74, 0xc7, 0xd5, 0xe8, 0x46,
	0x84, 0x79, 0x5c, 0x1d, 0x6c, 0xc3, 0xa2, 0x0c, 0xc1, 0xc1, 0x1c, 0x73, 0xcf, 0x61, 0x5d, 0x96,
	0x62, 0xb8, 0xb4, 0x5b, 0x91, 0x62, 0xe7, 0x60, 0xeb, 0x5d, 0x8a, 0x59, 0x57, 0x2e, 0x77, 0x69,
	0x17, 0xba, 0xc3, 0x3c, 0x8a, 0x43, 0x4e, 0xbe, 0x9e, 0x4a, 0x74, 0x06, 0x95, 0xa8, 0xc1, 0xd6,
	0x28, 0x7e, 0x84, 0xe1, 0x4b, 0x13, 0x35, 0x3e, 0x88, 0x12, 0x34, 0x08, 0x57, 0x37, 0x41, 0x8a,
	0xa6, 0x69, 0x5a, 0x1f, 0x50, 0x6c, 0x40, 0x21, 0xf7, 0x73, 0x70, 0xd3, 0x38, 0x18, 0x09, 0x74,
	0x74, 0x9e, 0xa0, 0xcd, 0xe8, 0x9a, 0x78, 0x2b, 0x44, 0xec, 0x12, 0xd2, 0x27, 0x80, 0x4a, 0xf0,
	0xf3, 0x93, 0x56, 0xad, 0x5b, 0x67, 0x3b, 0xea, 0x36, 0x4a, 0xdf, 0x6b, 0x13, 0xff, 0x0d, 0x6c,
	0x5e, 0xdf, 0x64, 0x22, 0x08, 0xfb, 0x52, 0xc6, 0x56, 0x7c, 0x9f, 0xae, 0xed, 0x4b, 0x70, 0x92,
	0x7c, 0xca, 0x35, 0x81, 0x8a, 0xec, 0xd4, 0x64, 0x80, 0x21, 0x4b, 0x57, 0xfe, 0x9f, 0x2b, 0xe0,
	0x1c, 0xd1, 0x45, 0xb7, 0x09, 0xbf, 0x40, 0x27, 0x14, 0x77, 0x11, 0xaa, 0x1c, 0xc9, 0x3c, 0xd1,
	0x98, 0xd1, 0xc0, 0xba, 0xed, 0x2e, 0xd6, 0x6d, 0x81, 0xde, 0x3b, 0x26, 0xee, 0x91, 0xa1, 0x9e,
	0x24, 0x3a, 0x9b, 0x31, 0x27, 0xac, 0x22, 0xe8, 0x99, 0xad, 0x08, 0xa3, 0x01, 0x76, 0x81, 0xa7,
	0x41, 0x86, 0x97, 0x02, 0x45, 0xab, 0x4a, 0x4e, 0x9d, 0xe4, 0x7c, 0x4c, 0x9c, 0xab, 0xb4, 0x5f,
	0x31, 0x0a, 0x75, 0xc5, 0x06, 0xd4, 0xc6, 0x47, 0x37, 0x68, 0xce, 0x37, 0x30, 0x3d, 0x7b, 0x64,
	0x83, 0xaf, 0xe1, 0x79, 0xae, 0xb0, 0xe2, 0xa6, 0x31, 0x45, 0xdd, 0xca, 0xdc, 0xb6, 0xb5, 0x10,
	0xc2, 0x7d, 0x6c, 0x91, 0x05, 0xcb, 0xb4, 0x00, 0xb6, 0x4a, 0xfa, 0xfc, 0xfd, 0x36, 0x8f, 0xa7,
	0x58, 0x61, 0xaf, 0x43, 0x55, 0x79, 0xb5, 0x58, 0x95, 0x47, 0xeb, 0xcf, 0xbc, 0x62, 0x9b, 0x73,
	0xab, 0xb0, 0x22, 0xb9, 0x9f, 0x81, 0xed, 0xf9, 0x54, 0xe0, 0x7d, 0x45, 0x7d, 0x91, 0x0c, 0xc9,
	0xa4, 0x4d, 0xf6, 0x74, 0x1e, 0xef, 0x53, 0xd8, 0x8c, 0xb0, 0xa2, 0x27, 0xe3, 0x28, 0xc6, 0x7d,
	0x14, 0x7a, 0xb0, 0x61, 0x46, 0x98, 0x8d, 0x9e, 0xda, 0xa0, 0xfb, 0x2d, 0x38, 0x66, 0x46, 0x96,
	0x8e, 0x5f, 0x21, 0xc7, 0x3f, 0x5b, 0xd4, 0x58, 0x0d, 0x57, 0x06, 0x48, 0x2d, 0x5d, 0x8e, 0xc3,
	0xc0, 0xce, 0x30, 0x25, 0xc7, 0xa8, 0xa5, 0x7c, 0xbb, 0xf7, 0xa1, 0x1d, 0x06, 0x84, 0x0d, 0x10,
	0xea, 0x97, 0x88, 0xc9, 0x88, 0xe5, 0x84, 0x17, 0xaa, 0xaa, 0x8c, 0x96, 0xcd, 0x40, 0xcc, 0x1a,
	0xa3, 0xca, 0xf8, 0x1e, 0x56, 0xc9, 0xef, 0x73, 0x79, 0x40, 0xf2, 0xbc, 0x07, 0xf2, 0x16, 0xee,
	0x3e, 0xeb, 0x4c, 0x16, 0x27, 0x01, 0xf6, 0x51, 0x62, 0x91, 0xc8, 0xed, 0x1c, 0x2f, 0xa9, 0x90,
	0xb9, 0xc6, 0xd6, 0xf0, 0xa9, 0xf2, 0x1c, 0xba, 0x8f, 0x1b, 0x73, 0xf8, 0xda, 0xa2, 0xe7, 0xc9,
	0xa5, 0x7a, 0xf1, 0x03, 0x74, 0x97, 0x1d, 0xea, 0x76, 0xa1, 0x71, 0x2b, 0x66, 0x74, 0x15, 0xda,
	0xcc, 0x3c, 0xba, 0x1b, 0xd0, 0xbc, 0x0b, 0xe2, 0x5c, 0x14, 0x7e, 0xb4, 0x8b, 0xef, 0xea, 0x6f,
	0x6a, 0xfe, 0x3f, 0xf8, 0x45, 0x62, 0x79, 0x52, 0xaa, 0x38, 0x04, 0x07, 0x9d, 0x8a, 0x27, 0xb6,
	0x53, 0xb0, 0x46, 0x53, 0xf0, 0x81, 0x0b, 0x2a, 0x72, 0xef, 0xda, 0x30, 0xed, 0x10, 0x04, 0x3d,
	0x7f, 0x76, 0x7d, 0x58, 0x7d, 0xa8, 0xbf, 0x4e, 0xfa, 0x1d, 0x5d, 0xc9, 0x76, 0xf7, 0x61, 0xe3,
	0x51, 0xdb, 0x59, 0x7f, 0xac, 0x47, 0xcb, 0x66, 0xf2, 0xf7, 0x00, 0xaa, 0xd7, 0xb9, 0x1d, 0x68,
	0xfd, 0x7a, 0xc5, 0xaf, 0xd9, 0x4f, 0x47, 0x27, 0x38, 0x66, 0xd7, 0x00, 0x4e, 0xdf, 0x5e, 0x5c,
	0x14, 0xeb, 0x9a, 0xff, 0x07, 0x38, 0xa8, 0xf2, 0x52, 0xe8, 0x20, 0x0c, 0x74, 0x80, 0x33, 0x16,
	0xaa, 0x0f, 0x31, 0x1d, 0xc9, 0x39, 0xd8, 0x5c, 0x3c, 0xd2, 0x00, 0xd1, 0x81, 0x01, 0x59, 0x5b,
	0x95, 0x8f, 0xe8, 0x35, 0xa8, 0x3e, 0xf5, 0x74, 0x84, 0xa5, 0x5e, 0x9a, 0xc9, 0x48, 0xfd, 0x3c,
	0x16, 0x63, 0xd6, 0x1e, 0x95, 0xab, 0xc3, 0x3d, 0xf0, 0x64, 0x36, 0x59, 0x64, 0xce, 0x7f, 0x10,
	0x1c, 0x76, 0x16, 0x26, 0x8b, 0xea, 0xd7, 0x86, 0x2b, 0xf4, 0xb3, 0xe0, 0xcb, 0xff, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x6e, 0x62, 0xb6, 0x59, 0xa3, 0x08, 0x00, 0x00,
}
