#!/bin/bash

set -e 

# Copy COpsDef 
printf "// Code generated by go:generate\n// DO NOT EDIT\n\npackage tensorflow\n\nconst COpsDef = \`%s\`" "`cat ../../core/ops/ops.pbtxt | tr \\\` \'`"> proto/tf_ops_def.go

# Generate protobuf
pushd .
cd ../../../
# generate tensorflow
protoc --go_out=tensorflow/contrib/go/proto/ \
    tensorflow/core/framework/*.proto\
    tensorflow/core/util/*.proto\
    tensorflow/core/protobuf/{config.proto,master.proto,meta_graph.proto,named_tensor.proto,queue_runner.proto,saver.proto,tensorflow_server.proto,worker.proto}

# generate tensorflow.error
protoc -I=. --go_out=tensorflow/contrib/go/proto/  tensorflow/core/lib/core/error_codes.proto

# generate tensorflow.grpc
protoc --go_out=plugin=grpc:tensorflow/contrib/go/proto/service tensorflow/core/protobuf/\
{master_service.proto,\
worker_service.proto\
}

popd 

# Move
mv ./proto/tensorflow/core/protobuf/*.pb.go ./proto
mv ./proto/tensorflow/core/framework/*.pb.go ./proto
mv ./proto/tensorflow/core/util/*.pb.go ./proto
mv ./proto/tensorflow/core/lib/core/*.pb.go ./proto/error 

mv ./proto/service/tensorflow/core/protobuf/*.pb.go ./proto/service 

rm -fr ./proto/tensorflow
rm -fr ./proto/service/tensorflow